-- Finalized Oracle schema with constraints, example data, and indices
-- Use with caution on a non-production database

-- Users
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(150) UNIQUE NOT NULL,
  email VARCHAR2(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Categories
CREATE TABLE categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  user_id NUMBER NOT NULL,
  CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_categories_user ON categories(user_id);

-- Budgets
CREATE TABLE budgets (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  name VARCHAR2(200) NOT NULL,
  amount NUMBER(12,2) NOT NULL,
  start_date DATE,
  end_date DATE,
  CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_budgets_user ON budgets(user_id);

-- Expenses
CREATE TABLE expenses (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  category_id NUMBER,
  amount NUMBER(12,2) NOT NULL,
  description VARCHAR2(4000),
  exp_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_expenses_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);
CREATE INDEX idx_expenses_user ON expenses(user_id);
CREATE INDEX idx_expenses_date ON expenses(exp_date);

-- Sample demo data (for quick demo only)
INSERT INTO users (username, email) VALUES ('demo_student', 'student@example.com');

-- Get demo user id
DECLARE
  v_user_id NUMBER;
BEGIN
  SELECT id INTO v_user_id FROM users WHERE username = 'demo_student' AND ROWNUM=1;
  INSERT INTO categories (name, user_id) VALUES ('Food', v_user_id);
  INSERT INTO categories (name, user_id) VALUES ('Transport', v_user_id);
  INSERT INTO budgets (user_id, name, amount, start_date) VALUES (v_user_id, 'Monthly Basic', 3000, SYSDATE);
  INSERT INTO expenses (user_id, category_id, amount, description, exp_date) VALUES (v_user_id, 1, 5.50, 'Coffee', SYSDATE-2);
END;
/

-- Example reporting view
CREATE OR REPLACE VIEW vw_monthly_category_summary AS
SELECT u.id AS user_id,
       EXTRACT(YEAR FROM e.exp_date) AS year,
       EXTRACT(MONTH FROM e.exp_date) AS month,
       c.name AS category,
       SUM(e.amount) AS total_spent
FROM expenses e
JOIN users u ON e.user_id = u.id
LEFT JOIN categories c ON e.category_id = c.id
GROUP BY u.id, EXTRACT(YEAR FROM e.exp_date), EXTRACT(MONTH FROM e.exp_date), c.name;
